import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,rm,stat} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {AsyncStore} from '../src/async-store.js';import {Store} from '../src/store.js';import {migrateMail} from '../src/mail-migration.js';import {DatabaseSync} from 'node:sqlite';
test('mail migration preserves both histories and approvals, excludes OAuth from backups and is idempotent',async()=>{const root=await mkdtemp(join(tmpdir(),'mail-migration-')),previous=process.env.MAIL_TO_CODE_CONFIG_DIR;process.env.MAIL_TO_CODE_CONFIG_DIR=root;await mkdir(join(root,'data'));const raw={gmailAddress:'agent@gmail.com',ownerAddress:'owner@example.test',engine:'async-cli',dataDir:join(root,'data'),oauthPort:8765};await writeFile(join(root,'config.json'),JSON.stringify(raw),{mode:0o600});await writeFile(join(root,'token.json'),'SYNTHETIC_OLD_OAUTH',{mode:0o600});const async=new AsyncStore(join(raw.dataDir,'async-cli.sqlite')),legacy=new Store(join(raw.dataDir,'state.sqlite'));async.meta('started_at','100');async.meta('gmail_cursor','old-provider-cursor');async.put('conversation','feature',{id:'feature',codexThread:'native-history',createdAt:'now'});async.put('input','old-input',{id:'old-input',status:'accepted',raw:'unchanged'});async.put('mail','mail',{status:'sent',identityStatus:'verified',rfcMessageId:'<provider@example.test>',text:'frozen'});async.put('approval','approval',{id:'approval',mailId:'mail',consumed:true});legacy.set('gmail_history','legacy-cursor');legacy.set('gmail_last_success','100000');const before=JSON.stringify(async.db.prepare('SELECT * FROM records ORDER BY kind,id').all());async.close();legacy.close();
try{const dry=await migrateMail(true,async()=>{});assert.equal(dry.dryRun,true);assert.deepEqual(JSON.parse(await readFile(join(root,'config.json'),'utf8')),raw);const result=await migrateMail(false,async()=>{});assert.equal(result.replayed,0);const config=JSON.parse(await readFile(join(root,'config.json'),'utf8'));assert.equal('oauthPort' in config,false);assert.equal((await stat(join(root,'config.json'))).mode&0o777,0o600);const migrated=new AsyncStore(join(raw.dataDir,'async-cli.sqlite'));assert.equal(migrated.meta('mail_scan_baseline'),'100000');assert.equal(migrated.meta('gmail_cursor'),'old-provider-cursor');assert.equal(JSON.stringify(migrated.db.prepare('SELECT * FROM records ORDER BY kind,id').all()),before);migrated.meta('mail_scan_success','200000');migrated.meta('mail_scan_full','200000');migrated.close();await migrateMail(false,async()=>{});const again=new AsyncStore(join(raw.dataDir,'async-cli.sqlite'));assert.equal(again.meta('mail_scan_success'),'200000');assert.equal(again.meta('mail_scan_full'),'200000');again.close();const backup=new DatabaseSync(join(result.backup!,'async-cli.sqlite'),{readOnly:true});assert.equal(JSON.stringify(backup.prepare('SELECT * FROM records ORDER BY kind,id').all()),before);backup.close();assert.equal(await stat(join(result.backup!,'token.json')).catch(()=>null),null);assert.equal(await readFile(join(root,'token.json'),'utf8'),'SYNTHETIC_OLD_OAUTH');}
finally{if(previous===undefined)delete process.env.MAIL_TO_CODE_CONFIG_DIR;else process.env.MAIL_TO_CODE_CONFIG_DIR=previous;await rm(root,{recursive:true,force:true});}});
test('migration refuses a live lease and unresolved native or external effects',async()=>{const root=await mkdtemp(join(tmpdir(),'mail-migration-block-')),previous=process.env.MAIL_TO_CODE_CONFIG_DIR;process.env.MAIL_TO_CODE_CONFIG_DIR=root;await mkdir(join(root,'data'));await writeFile(join(root,'config.json'),JSON.stringify({gmailAddress:'agent@gmail.com',ownerAddress:'owner@example.test',dataDir:join(root,'data')}),{mode:0o600});const store=new AsyncStore(join(root,'data/async-cli.sqlite'));store.meta('started_at','100');store.put('operation','uncertain',{status:'uncertain'});store.close();try{const result=await migrateMail(true,async()=>{});assert.deepEqual(result.databases[0].blockers,['operation:uncertain']);await assert.rejects(migrateMail(false,async()=>{}),/RECONCILE_FIRST/);await writeFile(join(root,'data/daemon.lock'),JSON.stringify({pid:process.pid}));await assert.rejects(migrateMail(true,async()=>{}),/Another/);}finally{if(previous===undefined)delete process.env.MAIL_TO_CODE_CONFIG_DIR;else process.env.MAIL_TO_CODE_CONFIG_DIR=previous;await rm(root,{recursive:true,force:true});}});

test('both stores reject changes to a frozen reply parent or attachment evidence',()=>{
 for(const store of [new AsyncStore(':memory:'),new Store(':memory:')]){
  try{const mail:any={id:'snapshot',sessionId:'task',kind:'test',text:'frozen',attachments:[],status:'sending',attempts:1,createdAt:'now',replyMessageId:'parent',replyParentRfcId:'<parent@example.test>',replyQuoteHash:'digest',attachmentHashes:[]};store.saveMail(mail);for(const key of ['replyMessageId','replyParentRfcId','replyQuoteHash','attachmentHashes']){const changed={...mail,[key]:key==='attachmentHashes'?['changed']:'changed'};assert.throws(()=>store.saveMail(changed),/IMMUTABLE_REPLY_PARENT_SNAPSHOT/);}assert.deepEqual(store.mail(mail.id),mail);}finally{store.close();}
 }
});
