import {installSemanticFixture,drainObservations,wire,synthetic} from './semantic-fixture.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {ConfigSchema} from '../src/config.js';
import {Store} from '../src/store.js';
import {Delivery} from '../src/delivery.js';
import {MultiController,manifest} from '../src/multi-controller.js';
import {ProjectRegistry} from '../src/projects.js';
import {currentBinding} from '../src/approval.js';
import {validateIntent,ReplyInterpreter} from '../src/reply-interpreter.js';
import {Runner,replyPolicy} from '../src/runner.js';
import {migrate} from '../src/migration.js';
import type {Session,ReplyIntent,Incoming,ReplyContext} from '../src/types.js';
import {fakeMail} from './fake-mail.js';
async function fixture(){
 const root=await mkdtemp(join(tmpdir(),'mail-replies-')),config=ConfigSchema.parse({gmailAddress:'agent@gmail.com',ownerAddress:'owner@qq.com',projectsRoot:root,productDocs:root,dataDir:join(root,'data')}),store=new Store(':memory:');store.migrate(s=>s);store.set('schema_version','4');
 const session:Session={id:'DEV-20261001-777',repo:'mini',title:'任务',subject:'[DEV-20261001-777] 任务',state:'WAITING_START',createdAt:new Date().toISOString(),initialMessageId:'initial',initialRfcId:'<initial@qq.com>',initialThreadId:'initial',threadId:'canonical',summary:'方案',targets:[],references:[],planManifest:'plan-v1',revision:0,cancellationEpoch:0};store.save(session);
 const mail=fakeMail(config),delivery=new Delivery(config,store,mail),work={interpretReply:async(s:Session,c:ReplyContext):Promise<ReplyIntent>=>({action:'start',clear:true,evidence:c.incoming.text,feedback:'',question:''})};
 const controller=new MultiController(config,store,mail,{} as any,new ProjectRegistry(config,store),work as any);
 installSemanticFixture(work,store);drainObservations(controller,store);
 // This fixture tests routing/interpretation transactions; business adapters are never executed.
 (controller as any).startBusiness=()=>undefined;
 async function notice(kind='plan'){
  const s=store.session(session.id)!;if(kind==='review')s.reviewManifest=manifest(s);const m=store.notify(s,kind,'方案内容');m.status='sent';const r=mail.record({subject:s.subject,text:m.text,deliveryMarker:m.deliveryMarker});m.gmailId=r.id;store.saveMail(m);await delivery.reconcile(m);
  if(kind==='plan')s.planNotice=m.id;else if(kind==='review'){s.reviewNotice=m.id;s.reviewManifest=manifest(s);}else s.mergeNotice=m.id;store.save(s);return store.mail(m.id)!;
 }
 const plan=await notice();let n=0;
 function incoming(text:string,reply=plan.rfcMessageId!):Incoming{return {id:'reply-'+(++n),rfcId:`<reply-${n}@qq.com>`,threadId:'canonical',inReplyTo:reply,subject:session.subject,text,from:config.ownerAddress,trusted:true};}
 return {root,config,store,mail,delivery,work,controller,notice,plan,incoming,s:()=>store.session(session.id)!,pending:()=>store.jobs().filter(j=>j.kind!=='interpret'&&j.status==='queued'),cleanup:async()=>{await controller.stop();store.close();await rm(root,{recursive:true,force:true});}};
}
test('Delivered Gmail RFC ID maps lowercase START to immutable notification exactly once',async()=>{const x=await fixture();try{assert.notEqual(x.plan.id,x.plan.rfcMessageId);const input=x.incoming('start');x.controller.handle(input);x.controller.handle(input);await x.controller.startNext();assert.equal(x.s().state,'QUEUED');assert.equal(x.pending().length,1);assert.equal(x.pending()[0].kind,'develop');}finally{await x.cleanup();}});
test('Help binds a version; reply succeeds, but the same help cannot authorize a changed plan',async()=>{const x=await fixture();try{
 x.controller.handle(x.incoming('START','<unknown>'));await x.controller.startNext();const help=x.store.mails().at(-1)!;assert.equal(help.kind,'help');assert.equal(help.approvalBinding!.noticeId,x.plan.id);await x.controller.flush();const delivered=x.store.mail(help.id)!;x.controller.handle(x.incoming('start',delivered.rfcMessageId));await x.controller.startNext();assert.equal(x.pending().length,1);
 const s=x.s();s.state='WAITING_START';s.summary='变更的方案';s.planManifest='plan-v2';x.store.save(s);for(const j of x.pending()){j.status='done';x.store.saveJob(j);}x.controller.handle(x.incoming('START',delivered.rfcMessageId));await x.controller.startNext();assert.equal(x.pending().length,0);assert.match(x.store.mails().at(-1)!.text,/旧通知|有效最新版本/);
}finally{await x.cleanup();}});
test('References can route a task but cannot grant approval without a bound direct reply',async()=>{const x=await fixture();try{const m=x.incoming('START','');m.threadId='new-thread';m.subject='回复';m.references=[x.plan.rfcMessageId!];x.controller.handle(m);assert.equal(x.pending().length,0);assert.equal(x.store.sessions().length,1);}finally{await x.cleanup();}});
test('Identity read failure after successful send is retried without sending again',async()=>{const x=await fixture();try{
 const original=x.mail.read;let sends=0;const send=x.mail.send;x.mail.send=async(v:any)=>{sends++;return send(v);};x.mail.read=async()=>{throw Error('read failed');};const m=x.store.notify(x.s(),'help','通知');await x.controller.flush();assert.equal(x.store.mail(m.id)!.status,'sent');assert.ok(x.store.mail(m.id)!.gmailId);assert.equal(x.store.mail(m.id)!.identityStatus,'pending');
 const next=x.store.notify(x.s(),'help','下一封');await x.controller.flush();assert.equal(sends,1);assert.equal(x.store.mail(next.id)!.status,'pending');x.mail.read=original;await x.delivery.reconcile(x.store.mail(m.id)!);await x.controller.flush();assert.equal(sends,2);assert.equal(x.store.mail(m.id)!.identityStatus,'verified');
}finally{await x.cleanup();}});
test('Unknown send reconciles by marker and full sent evidence; ambiguity and non-sent forgery remain blocked',async()=>{const x=await fixture();try{
 const m=x.store.notify(x.s(),'help','通知');m.status='uncertain';m.attemptedAt=new Date().toISOString();x.store.saveMail(m);const a=x.mail.record({subject:x.s().subject,text:m.text,deliveryMarker:m.deliveryMarker});let query='';x.mail.search=async(q:string)=>{query=q;return[a];};assert.equal(await x.delivery.reconcile(m),'verified');assert.match(query,new RegExp(m.deliveryMarker!));
 const ambiguous={...m,gmailId:undefined,status:'uncertain' as const};const b=x.mail.record({subject:x.s().subject,text:m.text,deliveryMarker:m.deliveryMarker});x.mail.search=async()=>[a,b];assert.equal(await x.delivery.reconcile(ambiguous),'ambiguous');assert.equal(ambiguous.status,'uncertain');
 const read=x.mail.read;x.mail.read=async(id:string)=>({...await read(id),labelIds:['INBOX']});x.mail.search=async()=>[a];assert.equal(await x.delivery.reconcile(ambiguous),'pending');assert.equal(ambiguous.status,'uncertain');
}finally{await x.cleanup();}});
test('Legacy mail without a marker backfills by Gmail ID or bounded verified candidates',async()=>{const x=await fixture();try{const m=x.store.notify(x.s(),'help','旧通知');delete m.deliveryMarker;m.status='uncertain';x.store.saveMail(m);const a=x.mail.record({subject:x.s().subject,text:m.text});let q='';x.mail.search=async(query:string)=>{q=query;return[a];};assert.equal(await x.delivery.reconcile(m),'verified');assert.match(q,/after:\d+ before:\d+/);assert.ok(m.rfcMessageId);}finally{await x.cleanup();}});
test('Subsequent messages use actual delivered reply/reference IDs',async()=>{const x=await fixture();try{let input:any;const send=x.mail.send;x.mail.send=async(v:any)=>{input=v;return send(v);};x.store.notify(x.s(),'help','下一封');await x.controller.flush();assert.equal(input.inReplyTo,x.plan.rfcMessageId);assert.deepEqual(input.references,[x.plan.rfcMessageId]);}finally{await x.cleanup();}});
test('Natural START is interpreted and applied once with its captured notification',async()=>{const x=await fixture();try{const m=x.incoming('按方案开始');x.controller.handle(m);assert.equal(x.s().state,'WAITING_START');assert.equal(x.store.jobs()[0].kind,'interpret');await x.controller.startNext();assert.equal(x.s().state,'QUEUED');assert.equal(x.pending().length,1);x.controller.handle(m);assert.equal(x.pending().length,1);}finally{await x.cleanup();}});
test('Interpretation cannot confirm a plan that changed while the model was running',async()=>{const x=await fixture();try{let finish!:(r:ReplyIntent)=>void,started!:()=>void;const began=new Promise<void>(r=>started=r);x.work.interpretReply=async()=>{started();return new Promise(r=>finish=r);};x.controller.handle(x.incoming('开始开发'));const pending=x.controller.startNext()!;await began;const s=x.s();s.summary='new';s.planManifest='new';x.store.save(s);finish({action:'start',clear:true,evidence:'开始开发',feedback:'',question:''});await pending;assert.equal(x.pending().length,0);assert.equal(x.s().state,'WAITING_START');}finally{await x.cleanup();}});
test('Earlier feedback is applied before a later English START; latest notification becomes invalid',async()=>{const x=await fixture();try{x.work.interpretReply=async(s,c)=>({action:'feedback',clear:true,evidence:c.incoming.text,feedback:c.incoming.text,question:''});x.controller.handle(x.incoming('同意，但修改标题'));x.controller.handle(x.incoming('START'));assert.deepEqual(x.store.jobs().map(j=>j.kind),['interpret','interpret']);await x.controller.startNext();await x.controller.startNext();assert.equal(x.pending().some(j=>j.kind==='develop'),false);assert.equal(x.pending().filter(j=>j.kind==='plan').length,1);}finally{await x.cleanup();}});
test('English CANCEL uses the same model entry and then cancels queued development',async()=>{const x=await fixture();try{let finish!:(r:ReplyIntent)=>void,started!:()=>void;const began=new Promise<void>(r=>started=r);x.work.interpretReply=async()=>{started();return new Promise(r=>finish=r);};x.controller.handle(x.incoming('开始开发'));const pending=x.controller.startNext()!;await began;x.controller.handle(x.incoming('CANCEL'));finish({action:'start',clear:true,evidence:'开始开发',feedback:'',question:''});await pending;x.work.interpretReply=async(s,c)=>({action:'cancel',clear:true,evidence:c.incoming.text,feedback:'',question:''});await x.controller.startNext();assert.equal(x.s().state,'CANCELLED');assert.equal(x.pending().length,0);assert.equal(x.store.jobs()[0].status,'done');}finally{await x.cleanup();}});
test('Read-only interpretation can run while a business job is active',async()=>{const x=await fixture();try{const j=x.store.enqueue(x.s(),'develop','existing');j.status='running';x.store.saveJob(j);x.work.interpretReply=async(s,c)=>({action:'status',clear:true,evidence:c.incoming.text,feedback:'',question:''});x.controller.handle(x.incoming('现在进展如何'));await x.controller.startNext();assert.equal(x.store.jobs().find(v=>v.id===j.id)!.status,'running');assert.equal(x.store.jobs().filter(v=>v.kind==='interpret')[0].status,'done');}finally{await x.cleanup();}});
test('Interpreter failure leaves business state intact; RETRY reuses the stored envelope',async()=>{const x=await fixture();try{x.work.interpretReply=async()=>{throw Error('CODEX_TIMEOUT');};x.controller.handle(x.incoming('开始开发'));await x.controller.startNext();assert.equal(x.s().state,'WAITING_START');assert.equal(x.store.jobs()[0].status,'failed');x.work.interpretReply=async(s,c)=>({action:'start',clear:true,evidence:c.incoming.text,feedback:'',question:''});x.controller.handle(x.incoming('RETRY'));await x.controller.startNext();await x.controller.startNext();assert.equal(x.pending().length,1);}finally{await x.cleanup();}});
test('Restart requeues unfinished interpretation without failing the business task; applied decisions stay done',async()=>{const x=await fixture();try{x.controller.handle(x.incoming('开始开发'));let j=x.store.jobs()[0];j.status='running';x.store.saveJob(j);x.store.recover();assert.equal(x.s().state,'WAITING_START');assert.equal(x.store.jobs()[0].status,'queued');await x.controller.startNext();j=x.store.jobs()[0];assert.equal(j.status,'done');x.store.recover();assert.equal(x.store.jobs()[0].status,'done');}finally{await x.cleanup();}});
test('Semantic APPROVE and DEPLOY are distinct and retain controller self-maintenance restrictions',async()=>{const x=await fixture();try{
 let s=x.s();s.state='WAITING_REVIEW';x.store.save(s);const review=await x.notice('review');x.work.interpretReply=async(s,c)=>({action:'approve',clear:true,evidence:c.incoming.text,feedback:'',question:''});x.controller.handle(x.incoming('同意合并',review.rfcMessageId));await x.controller.startNext();assert.equal(x.pending()[0].kind,'merge');assert.equal(x.pending().some(j=>j.kind==='deploy'),false);
 for(const j of x.pending()){j.status='done';x.store.saveJob(j);}s=x.s();s.state='WAITING_REVIEW';s.targets=[{projectId:'mail-to-code',manualMerge:true} as any];s.reviewManifest=manifest(s);x.store.save(s);const manual=await x.notice('review');x.controller.handle(x.incoming('APPROVE',manual.rfcMessageId));await x.controller.startNext();assert.equal(x.pending().length,0);assert.match(x.store.mails().at(-1)!.text,/手动合并/);
}finally{await x.cleanup();}});
test('Schema/evidence reject injected actions, unknown projects, and bare merge/production acknowledgements',()=>{
 const s={targets:[{projectId:'mini'}]} as Session,c={incoming:{text:'可以'}} as ReplyContext;
 for(const action of ['approve','deploy'] as const)assert.equal(validateIntent({action,clear:true,evidence:'可以',feedback:'',project:null,question:''},c,s).action,action);
 assert.throws(()=>validateIntent({action:'start',clear:true,evidence:'开始',feedback:'',project:null,question:''},c,s),/EVIDENCE/);
 assert.throws(()=>validateIntent({action:'deploy',clear:true,evidence:'可以',feedback:'',project:'outside',question:''},c,s),/PROJECT/);
 assert.throws(()=>validateIntent({action:'shell',clear:true,evidence:'可以',feedback:'',project:null,question:''},c,s));
});
test('Interpreter uses a fresh context and minimal policy, never project/development sessions',async()=>{const x=await fixture();try{
 const original=(Runner.prototype as any).interpret;let calls:any[]=[];(Runner.prototype as any).interpret=async(dir:string,schema:any,prompt:string)=>{calls.push({dir,prompt,config:(undefined)});return {...wire({items:[{id:'start',action:'start',clear:true,evidence:'开始开发',text:'',project:undefined,questionRefs:[],dependsOn:[]}],questions:[]}),items:[{id:'start',action:'start',clear:true,evidence:'开始开发',text:'',project:null,questionRefs:[],dependsOn:[]}]};};
 try{await new ReplyInterpreter(x.config).interpret({...x.s(),analysisThreadId:'analysis',thread:'development'},{incoming:x.incoming('开始开发'),epoch:0,binding:currentBinding(x.s())},new AbortController().signal);assert.equal(calls.length,1);assert.ok(calls[0].dir.startsWith(join(x.config.dataDir,'reply-runs')));assert.ok(!calls[0].prompt.includes('development'));const policy=replyPolicy(calls[0].dir).join(' ');assert.match(policy,/:root.*deny/);assert.match(policy,/network.enabled=false/);assert.match(policy,/plugins=false/);assert.match(policy,/hooks=false/);assert.ok(!policy.includes(x.config.projectsRoot+'"="read'));}finally{(Runner.prototype as any).interpret=original;}
}finally{await x.cleanup();}});
test('v3 to v5 migration preserves live notification/session data and prevents older code compatibility',async()=>{const x=await fixture();try{x.store.set('schema_version','3');x.store.set('gmail_history','cursor');const before=x.store.session(x.s().id);const out=x.store.mails();const result=await migrate(x.config,x.store,new ProjectRegistry(x.config,x.store),async()=>false);assert.equal(result.version,7);const after=x.store.session(x.s().id)!;assert.equal(after.workflow?.legacy,true);delete after.workflow;assert.deepEqual(after,before);assert.deepEqual(x.store.mails(),out);assert.equal(x.store.get('gmail_history'),'cursor');assert.equal(x.store.get('reply-recovery-required:'+x.s().id),'1');assert.ok(result.backup);assert.ok((await readFile(result.backup!)).length>0);assert.equal(x.store.jobs().length,0);}finally{await x.cleanup();}});
test('Failed earlier reply prevents later authorization; natural RETRY releases FIFO without losing decisions',async()=>{const x=await fixture();try{
 x.work.interpretReply=async()=>{throw Error('CODEX_TIMEOUT');};x.controller.handle(x.incoming('先修改标题'));await x.controller.startNext();
 x.controller.handle(x.incoming('START'));assert.equal(x.pending().length,0);
 x.work.interpretReply=async(s,c)=>({action:c.incoming.text==='重试'?'retry':'start',clear:true,evidence:c.incoming.text,feedback:'',question:''});x.controller.handle(x.incoming('按方案开始'));await x.controller.startNext();assert.equal(x.pending().length,0);assert.equal(x.store.jobs().filter(j=>j.reply?.waitingForEarlier).length,2);
 x.controller.handle(x.incoming('重试'));await x.controller.startNext();assert.equal(x.store.jobs()[0].status,'queued');
 x.work.interpretReply=async(s,c)=>({action:'feedback',clear:true,evidence:c.incoming.text,feedback:c.incoming.text,question:''});await x.controller.startNext();await x.controller.startNext();assert.equal(x.pending().some(j=>j.kind==='develop'),false);assert.equal(x.pending().filter(j=>j.kind==='plan').length,1);
}finally{await x.cleanup();}});
test('Semantic explicit deployment chooses its confirmed project and merged commit; ambiguous target does not queue',async()=>{const x=await fixture();try{
 const s=x.s();s.state='MERGED';s.repo='mini';s.targets=[{projectId:'mini',mergeSha:'merged-sha',identity:'mini',profileVersion:'profile',deployment:{enabled:true}} as any,{projectId:'docs',mergeSha:'docs-sha',identity:'docs',profileVersion:'docs-profile'} as any];x.store.save(s);const merged=await x.notice('merge');
 x.work.interpretReply=async(s,c)=>({action:'deploy',clear:true,evidence:c.incoming.text,feedback:'',question:'',project:'mini'});x.controller.handle(x.incoming('确认发布小程序',merged.rfcMessageId));await x.controller.startNext();assert.equal(x.pending().length,1);assert.equal(x.pending()[0].kind,'deploy');assert.equal(x.pending()[0].feedback,'mini');assert.equal(x.s().deployTarget,'mini');
}finally{await x.cleanup();}});
test('Mixed English command and changes enter semantic feedback, never quick-path START',async()=>{const x=await fixture();try{x.work.interpretReply=async(s,c)=>({action:'feedback',clear:true,evidence:c.incoming.text,feedback:c.incoming.text,question:''});x.controller.handle(x.incoming('START\n但先修改标题'));assert.equal(x.store.jobs()[0].kind,'interpret');await x.controller.startNext();assert.equal(x.pending().length,1);assert.equal(x.pending()[0].kind,'plan');}finally{await x.cleanup();}});
test('Natural STATUS remains available after cancellation; old-epoch intents cannot resume work',async()=>{const x=await fixture();try{x.controller.handle(x.incoming('CANCEL'));await x.controller.startNext();x.work.interpretReply=async(s,c)=>({action:'status',clear:true,evidence:c.incoming.text,feedback:'',question:''});x.controller.handle(x.incoming('现在状态如何'));await x.controller.startNext();assert.equal(x.store.jobs().at(-1)!.status,'done');assert.match(x.store.mails().at(-1)!.text,/CANCELLED/);assert.equal(x.pending().length,0);}finally{await x.cleanup();}});
test('The 60-second deadline includes setup and propagates an aborted signal without launching more work',async()=>{const x=await fixture();try{
 const originalTimeout=AbortSignal.timeout,original=(Runner.prototype as any).interpret;let propagated=false;
 AbortSignal.timeout=()=>AbortSignal.abort(new Error('synthetic deadline'));
 (Runner.prototype as any).interpret=async(dir:string,schema:any,prompt:string,signal:AbortSignal)=>{propagated=signal.aborted;signal.throwIfAborted();};
 try{await assert.rejects(new ReplyInterpreter(x.config).interpret(x.s(),{incoming:x.incoming('开始开发'),epoch:0},new AbortController().signal),/REPLY_TIMEOUT/);assert.equal(propagated,true);}finally{AbortSignal.timeout=originalTimeout;(Runner.prototype as any).interpret=original;}
}finally{await x.cleanup();}});
