import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,chmod,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {ConfigSchema} from '../src/config.js';
import {Store} from '../src/store.js';
import {ProjectRegistry} from '../src/projects.js';
import {MultiWork} from '../src/multi-work.js';
import {MultiController} from '../src/multi-controller.js';
import {git} from '../src/git.js';
import {Runner,codexPolicy} from '../src/runner.js';
import {fakeMail} from './fake-mail.js';
import {markdownChecks} from '../src/runtime.js';
import {migrate} from '../src/migration.js';
import {approvalVersion,currentBinding,bindingValid} from '../src/approval.js';
import {readWorkflowGuide,initializeWorkflowGuide,ensureWorkflow,advanceDocumentation,WorkflowProposalSchema} from '../src/workflow.js';
import type {Session,RepoExecution,Incoming} from '../src/types.js';
import type {Work} from '../src/controller.js';
const abort=()=>new AbortController().signal;
const proposal=(kind:'documentation'|'implementation'|'maintenance'='documentation')=>({decision:'propose_step' as const,kind,name:kind==='documentation'?'编写产品文档':'实施已确认设计',rationale:'按用户需求与现有记录推进',deliverables:[kind==='documentation'?'PRD 与 Design':'代码与产品证据'],acceptance:['相关检查通过']});
async function fixture(){
 const root=await mkdtemp(join(tmpdir(),'mail-workflow-')),projects=join(root,'projects');await mkdir(projects);
 for(const name of ['product-records','app']){const path=join(projects,name);await mkdir(path);await git(path,['init','-b','main']);await git(path,['config','user.name','test']);await git(path,['config','user.email','test@example.com']);await writeFile(join(path,'README.md'),'fixture');if(name==='product-records'){await mkdir(join(path,'ideas'));await writeFile(join(path,'ideas/DEMO-0002-images.md'),'# Images\n');await mkdir(join(path,'backlog'));await writeFile(join(path,'backlog/TODO.md'),'DEMO-0002: PRD\n');}await git(path,['add','.']);await git(path,['commit','-m','initial']);await git(path,['remote','add','origin',`https://github.com/example-org/${name}.git`]);await git(path,['update-ref','refs/remotes/origin/main','HEAD']);}
 const config=ConfigSchema.parse({gmailAddress:'a@gmail.com',ownerAddress:'o@qq.com',projectsRoot:projects,productDocs:join(projects,'product-records'),dataDir:join(root,'state'),previewEnabled:false,profiles:{app:{checks:[{executable:'node',args:['--version']}]}}}),store=new Store(join(root,'state.sqlite'));store.migrate(s=>s);store.set('schema_version','5');
 const registry=new ProjectRegistry(config,store,(path,branch,s)=>git(path,['fetch',path,`+refs/heads/${branch}:refs/remotes/origin/${branch}`],{signal:s}));
 const work=new MultiWork(config,store),runs:{stage:string;project:string;thread?:string}[]=[],made:string[]=[];let next='implementation',invalidScope=false,failMerge=false,modelComplete=false;
 work.analyze=async(s,_feedback,_sig,onThread)=>{onThread('analysis-retained');const kind=s.workflow?.history.length?next as 'implementation':'documentation';return{workflow:{...proposal(kind),...(modelComplete?{decision:'complete' as const}:{})},outcome:'plan_ready',summary:kind==='documentation'?'PRD 草案及设计建议，代码暂不修改':'按已合并设计实现',questions:[],memoryProposals:[],productId:'DEMO-0002',projects:kind==='documentation'?[{path:'product-records',displayName:'产品文档',role:'modify',pendingChecks:[]},{path:'app',displayName:'应用',role:invalidScope?'modify':'reference',pendingChecks:[]}]:[{path:'app',displayName:'应用',role:'modify',pendingChecks:[]},{path:'product-records',displayName:'产品证据',role:'product_record',pendingChecks:[]}],mergeOrder:kind==='documentation'?['product-records']:['app','product-records']};};
 const adapters=work.adapters.bind(work);work.adapters=(s,t)=>{const a=adapters(s,t);a.github.verify=async()=>{};a.runtime.verify=async()=>{};
  a.runner.run=async(view,_phase,_feedback,_sig,onThread)=>{runs.push({stage:s.workflow!.stageId,project:t.projectId,thread:view.thread});onThread('thread-'+s.workflow!.stageId+'-'+t.projectId);if(t.projectId==='product-records'){for(const d of ['prd','design']){await mkdir(join(view.worktree!,d),{recursive:true});await writeFile(join(view.worktree!,d,'DEMO-0002-images.md'),'# '+d+'\n');}await writeFile(join(view.worktree!,'backlog/TODO.md'),'DEMO-0002: Review\n');}else await writeFile(join(view.worktree!,'feature.txt'),'implemented');return{outcome:'implementation_ready',summary:'已修改，检查由控制器执行',questions:[],requiresBackend:false,screenshotTargets:[]};};return a;};
 work.prepare=async(s,t)=>{if(t.worktree)return;const view=work.view(s,t);t.branch='codex/'+view.id;t.worktree=join(root,view.id);await git(t.path,['worktree','add','-b',t.branch,t.worktree,t.baseSha!]);made.push(t.worktree);};
 work.review=async(s,t)=>{await git(t.worktree!,['add','.']);await git(t.worktree!,['commit','--allow-empty','-m','review']);t.reviewSha=await git(t.worktree!,['rev-parse','HEAD']);t.prNumber=s.workflow!.number;t.prUrl=`https://github.com/example-org/${t.projectId}/pull/${t.prNumber}`;t.checks=t.projectId==='product-records'?await markdownChecks(t.worktree!):['synthetic test passed'];};
 work.updateBase=async()=>{};work.inspect=async(_s,t)=>t.mergeSha;
 work.merge=async(_s,t)=>{if(failMerge)throw Error('merge conflict');await git(t.path,['update-ref','refs/heads/main',t.reviewSha!]);return t.reviewSha!;};
 const controller=new MultiController(config,store,fakeMail(config),{} as Work,registry,work);let n=0;
 const task=()=>store.sessions().find(s=>!s.system)!;
 const message=(text:string,reply='',subject?:string):Incoming=>({id:'m'+(++n),rfcId:`<${n}@qq.com>`,threadId:'workflow-thread',inReplyTo:reply,subject:subject||task()?.subject||'图片优化',text,from:config.ownerAddress,trusted:true});
 const flush=async()=>{while(store.mails().some(m=>m.status==='pending'))await controller.flush();};
 const plan=async()=>{controller.handle(message('PRODUCT: DEMO-0002\n请先起草 PRD 和设计建议','', '示例笔记图片优化'));await controller.startNext();await flush();};
 const develop=async()=>{controller.handle(message('START',task().planNotice));await controller.startNext();await flush();};
 const merge=async()=>{controller.handle(message('APPROVE',task().reviewNotice));await controller.startNext();await flush();};
 return{root,projects,config,store,registry,work,controller,task,message,flush,plan,develop,merge,runs,made,setInvalid:()=>invalidScope=true,setConflict:()=>failMerge=true,setComplete:()=>modelComplete=true,setNext:(v:string)=>next=v,cleanup:async()=>{await controller.stop();store.close();await rm(root,{recursive:true,force:true});}};
}
test('Incomplete/default-branch documents return inventory and versions instead of blocking',async()=>{const x=await fixture();try{
 const docs=await x.registry.documents('DEMO-0002',undefined,{sync:true});assert.deepEqual(docs.missing,['prd','design']);assert.equal(docs.files.length,1);
 const empty=await x.registry.documents('DEMO-9999');assert.deepEqual(empty.missing,['ideas','prd','design']);assert.equal(empty.files.length,0);
 const path=x.config.productDocs;await mkdir(join(path,'prd'));await writeFile(join(path,'prd/DEMO-0002-images.md'),'new uncommitted');assert.equal((await x.registry.documents('DEMO-0002')).version,docs.version);
 await git(path,['add','.']);await git(path,['commit','-m','new PRD']);const changed=await x.registry.documents('DEMO-0002',undefined,{sync:true});assert.deepEqual(changed.missing,['design']);assert.notEqual(changed.version,docs.version);
}finally{await x.cleanup();}});
test('Document stage is read-only before START, invokes Codex after START, checks docs and leaves business reference untouched',async()=>{const x=await fixture();try{
 await x.plan();assert.equal(x.task().state,'WAITING_START');assert.equal(x.made.length,0);assert.equal(x.runs.length,0);assert.deepEqual(x.task().targets!.map(t=>t.projectId),['product-records']);assert.equal(x.task().targets![0].auxiliary,false);assert.equal(x.task().references![0].projectId,'app');assert.match(x.store.mail(x.task().planNotice!)!.text,/PRD 草案/);
 await x.develop();assert.equal(x.task().state,'WAITING_REVIEW');assert.deepEqual(x.runs.map(r=>r.project),['product-records']);assert.equal(x.made.length,1);assert.ok(x.task().targets![0].checks!.length);assert.equal(x.task().targets![0].attachments,undefined);assert.equal(await readFile(join(x.projects,'app/README.md'),'utf8'),'fixture');
 const policy=codexPolicy(x.config,x.task().targets![0].worktree!,'develop',[x.task().references![0].baselineSnapshot!]);assert.ok(policy.some(p=>p.includes('"'+x.task().references![0].baselineSnapshot+'"="read"')));
}finally{await x.cleanup();}});
test('Document merge archives one stage and only plans the next; old START/Review/help cannot approve it',async()=>{const x=await fixture();try{
 await x.plan();const oldPlan=x.task().planNotice!,oldBinding=currentBinding(x.task())!;x.controller.handle(x.message('STATUS'));await x.flush();const oldHelp=x.store.mails().at(-1)!.id;await x.develop();const oldReview=x.task().reviewNotice!,oldTree=x.task().targets![0].worktree!;
 await x.merge();const s=x.task();assert.equal(s.workflow!.history[0].mergeNotice,undefined);assert.equal(x.store.mails().filter(m=>m.kind==='merge').length,0);const internal=x.store.db.prepare("SELECT data FROM events WHERE session_id=? AND event='notification_internal'").all(s.id).map(row=>JSON.parse(String(row.data)));assert.ok(internal.some(e=>e.kind==='merge'&&/新阶段需要新的 START/.test(e.text)));assert.equal(s.workflow!.history.length,1);assert.equal(s.workflow!.number,2);assert.equal(s.state,'QUEUED');assert.equal(x.store.jobs().filter(j=>j.kind==='plan'&&j.status==='queued').length,1);assert.equal(advanceDocumentation(s),false);assert.equal(x.made.length,1);assert.equal(x.runs.length,1);
 await x.controller.startNext();await x.flush();assert.equal(x.task().state,'WAITING_START',JSON.stringify(x.store.mails().slice(-2).map(m=>m.text)));assert.equal(x.task().workflow!.proposal!.kind,'implementation');assert.equal(x.task().targets!.every(t=>!t.worktree&&!t.thread&&!t.mergeSha),true);assert.equal(x.made.length,1);assert.equal(bindingValid(x.task(),oldBinding),false);
 for(const [cmd,id]of [['START',oldPlan],['START',oldHelp],['APPROVE',oldReview]])x.controller.handle(x.message(cmd,id));assert.equal(x.task().state,'WAITING_START');assert.equal(x.runs.length,1);
 await x.develop();assert.equal(x.task().state,'WAITING_REVIEW');assert.equal(x.made.length,3);assert.deepEqual(x.runs.map(r=>r.project),['product-records','app']);assert.notEqual(x.task().targets!.find(t=>t.projectId==='product-records')!.worktree,oldTree);assert.equal(x.task().workflow!.history[0].targets[0].worktree,oldTree);assert.equal(x.task().analysisThreadId,'analysis-retained');
}finally{await x.cleanup();}});
test('Out-of-scope documentation proposal is rejected before a worktree or START',async()=>{const x=await fixture();try{x.setInvalid();await x.plan();assert.equal(x.task().state,'FAILED');assert.match(x.task().lastError!,/只能声明/);assert.equal(x.made.length,0);}finally{await x.cleanup();}});
test('Merge conflict and cancellation preserve current stage; no next stage is queued',async()=>{const x=await fixture();try{await x.plan();await x.develop();x.setConflict();await x.merge();assert.equal(x.task().state,'QUEUED');assert.equal(x.task().targets![0].mergeSha,undefined);assert.equal(x.task().workflow!.history.length,0);assert.equal(x.store.jobs().filter(j=>j.kind==='plan'&&j.status==='queued').length,0);x.controller.handle(x.message('CANCEL'));x.store.recover();assert.equal(x.task().state,'CANCELLED');assert.equal(x.task().workflow!.number,1);}finally{await x.cleanup();}});
test('Restart preserves completed transition without repeating stage advancement or execution',async()=>{const x=await fixture();try{await x.plan();await x.develop();await x.merge();x.store.recover();x.store.recover();assert.equal(x.store.jobs().filter(j=>j.kind==='plan'&&j.status==='queued').length,1);assert.equal(x.task().workflow!.history.length,1);assert.equal(x.runs.length,1);}finally{await x.cleanup();}});
test('Known completed document merge is recovered atomically after interruption; uncertainty never advances',async()=>{const x=await fixture();try{await x.plan();await x.develop();const s=x.task();s.state='MERGED';s.targets![0].mergeSha=s.targets![0].reviewSha;s.mergeUncertain='product-records';x.store.save(s);const job=x.store.enqueue(s,'merge','');job.status='running';x.store.saveJob(job);x.store.recover();assert.equal(x.task().workflow!.number,1);s.mergeUncertain=undefined;s.state='MERGED';x.store.save(s);job.status='running';x.store.saveJob(job);x.store.recover();assert.equal(x.task().workflow!.number,2);assert.equal(x.store.jobs().filter(j=>j.kind==='plan'&&j.status==='queued').length,1);}finally{await x.cleanup();}});
test('Guide initializes once, refuses symlinks/secrets, and edits invalidate unstarted plans only',async()=>{const x=await fixture();const old=process.env.MAIL_TO_CODE_CONFIG_DIR;try{
 const dir=join(x.root,'config');await initializeWorkflowGuide(dir);const initial=await readWorkflowGuide(dir);await writeFile(join(dir,'WORKFLOW.md'),initial.text+'\nHuman convention\n',{mode:0o600});assert.equal((await initializeWorkflowGuide(dir)).created,false);assert.notEqual((await readWorkflowGuide(dir)).version,initial.version);
 process.env.MAIL_TO_CODE_CONFIG_DIR=dir;await x.plan();const before=x.task();await writeFile(join(dir,'WORKFLOW.md'),initial.text+'\nNew workflow\n',{mode:0o600});await assert.rejects(x.work.verifyPlan(before,x.registry,abort()),/工作流指南变化/);before.workflow!.confirmed=true;await x.work.verifyPlan(before,x.registry,abort());
 await writeFile(join(dir,'WORKFLOW.md'),'password=unsafe',{mode:0o600});await assert.rejects(readWorkflowGuide(dir),/credentials/);await rm(join(dir,'WORKFLOW.md'));await symlink(join(x.projects,'app/README.md'),join(dir,'WORKFLOW.md'));await assert.rejects(readWorkflowGuide(dir),/regular file/);
}finally{if(old===undefined)delete process.env.MAIL_TO_CODE_CONFIG_DIR;else process.env.MAIL_TO_CODE_CONFIG_DIR=old;await x.cleanup();}});
test('Workflow decisions clarify or complete without performing more work',async()=>{const x=await fixture();try{await x.plan();await x.develop();await x.merge();x.setComplete();await x.controller.startNext();assert.equal(x.task().state,'DONE');assert.equal(x.store.mails().filter(m=>m.kind==='complete').length,1);assert.equal(x.store.mails().some(m=>m.kind==='merge'),false);assert.equal(x.runs.length,1);assert.equal(x.task().workflow!.history.length,1);assert.throws(()=>WorkflowProposalSchema.parse({...proposal(),shell:'rm'}));}finally{await x.cleanup();}});
test('v4 migration preserves all existing task fields, approvals, outbox and cursor while protecting v5 state',async()=>{const x=await fixture();try{
 await x.plan();const s=x.task();delete s.workflow;x.store.save(s);x.store.set('schema_version','4');x.store.set('gmail_history','unchanged');const before=structuredClone(s),version=approvalVersion(s,'START'),out=x.store.mails(),jobs=x.store.jobs();
 const result=await migrate(x.config,x.store,x.registry,async()=>false);assert.equal(result.version,6);assert.equal(x.store.session(s.id)!.workflow!.legacy,true);const after=x.store.session(s.id)!;assert.equal(approvalVersion(after,'START'),version);delete after.workflow;assert.deepEqual(after,before);assert.deepEqual(x.store.mails(),out);assert.deepEqual(x.store.jobs(),jobs);assert.equal(x.store.get('gmail_history'),'unchanged');assert.equal(x.store.get('schema_version'),'6');const backup=new DatabaseSync(result.backup!,{readOnly:true});assert.equal(backup.prepare("SELECT value FROM meta WHERE key='schema_version'").get()!.value,'4');backup.close();
}finally{await x.cleanup();}});

test('A document target can run Codex and append implementation evidence to the same PR',async()=>{const x=await fixture();try{
 await x.plan();await x.develop();await x.merge();const analyze=x.work.analyze.bind(x.work);x.work.analyze=async(...args)=>{const result=await analyze(...args);for(const p of result.projects)if(p.path==='product-records')p.role='modify';return result;};
 await x.controller.startNext();await x.flush();await x.develop();assert.equal(x.task().state,'WAITING_REVIEW');assert.deepEqual(x.runs.map(r=>r.project),['product-records','app','product-records']);const docs=x.task().targets!.find(t=>t.projectId==='product-records')!;assert.equal(docs.auxiliary,false);assert.equal(docs.recordEvidence,true);const todo=await readFile(join(docs.worktree!,'backlog/TODO.md'),'utf8');assert.match(todo,/s2\/r2\/README.md/);assert.match(todo,/example-org\/app\/pull\/2/);assert.equal(x.task().targets!.at(-1)!.projectId,'product-records');
 await x.merge();assert.equal(x.task().state,'MERGED');assert.equal(x.task().workflow!.number,2);assert.equal(x.task().workflow!.history.length,1);assert.equal(x.store.jobs().some(j=>j.kind==='deploy'),false);
}finally{await x.cleanup();}});
test('START with an edited workflow or moved product baseline queues a new read-only plan',async()=>{const x=await fixture();const old=process.env.MAIL_TO_CODE_CONFIG_DIR;try{
 const dir=join(x.root,'config');await initializeWorkflowGuide(dir);process.env.MAIL_TO_CODE_CONFIG_DIR=dir;await x.plan();const beforeMail=x.store.mails();const notice=x.task().planNotice!;const guide=await readWorkflowGuide(dir);await writeFile(join(dir,'WORKFLOW.md'),guide.text+'\nUpdated policy\n',{mode:0o600});x.controller.handle(x.message('START',notice));await x.controller.startNext();assert.deepEqual(x.store.mails(),beforeMail);assert.equal(x.task().planNotice,undefined);assert.equal(x.made.length,0);assert.equal(x.store.jobs().filter(j=>j.kind==='plan'&&j.status==='queued').length,1);await x.controller.startNext();await x.flush();assert.equal(x.task().state,'WAITING_START');
 const latest=x.task().planNotice!;await writeFile(join(x.config.productDocs,'ideas/DEMO-0002-images.md'),'Changed Idea');await git(x.config.productDocs,['add','.']);await git(x.config.productDocs,['commit','-m','updated product']);x.controller.handle(x.message('START',latest));await x.controller.startNext();assert.equal(x.made.length,0);assert.equal(x.task().planNotice,undefined);assert.equal(x.store.jobs().filter(j=>j.kind==='plan'&&j.status==='queued').length,1);
}finally{if(old===undefined)delete process.env.MAIL_TO_CODE_CONFIG_DIR;else process.env.MAIL_TO_CODE_CONFIG_DIR=old;await x.cleanup();}});
test('clarify decision returns questions and maintenance can proceed without product documents',async()=>{const x=await fixture();try{
 x.work.analyze=async()=>({workflow:{...proposal(),decision:'clarify'},outcome:'needs_input',summary:'需要澄清',questions:['先 PRD 还是先测量？'],projects:[],memoryProposals:[],mergeOrder:[]});await x.plan();assert.equal(x.task().state,'WAITING_INPUT');assert.match(x.store.mails().at(-1)!.text,/先 PRD/);assert.equal(x.made.length,0);
 const s=x.task();s.productId=undefined;s.explicitProductId=undefined;x.store.save(s);x.work.analyze=async()=>({workflow:proposal('maintenance'),outcome:'plan_ready',summary:'维护脚本',questions:[],projects:[{path:'app',displayName:'应用',role:'modify',pendingChecks:[]}],memoryProposals:[],mergeOrder:['app']});const job=x.store.enqueue(s,'plan','维护');await (x.controller as any).executeMulti(job,abort());assert.equal(x.task().state,'WAITING_START');assert.equal(x.task().targets!.length,1);assert.equal(x.task().workflow!.documents!.files.length,0);
}finally{await x.cleanup();}});
